### PR TITLE
Update SFT token metadata

### PR DESCRIPTION
**Pull request by nvzvhenry**
# Update SFT token metadata

ERC-20: https://etherscan.io/address/0x0aabcc65ef352ad84b1326df188c95b6ab856c1c
NEP-141: https://explorer.mainnet.near.org/accounts/aabcc65ef352ad84b1326df188c95b6ab856c1c.factory.bridge.near
Aurora ERC-20 (Blockscout): https://explorer.mainnet.aurora.dev/address/0xfc56694ab428e7b4a03b8299b502d4598d945217
Aurora ERC-20 (Aurorascan): https://aurorascan.dev/address/0xfc56694ab428e7b4a03b8299b502d4598d945217

### CODE REVIEW

**Review by sept-en — CHANGES_REQUESTED** [review]
A duplicate for #153. Please just wait for the metadata update.

**Comment by nvzvhenry** [comment]
It's not a duplicate. The addresses were changed because there was an update on the Smart Contracts from Ethereum and so a new bridge was created. 

I updated with the new details.

**Comment by sept-en** [comment]
@nvzvhenry ok. then please resolve conflicts first and then it will be reviewed & merged.

**Review by sept-en — APPROVED** [review]

**Comment by nvzvhenry** [comment]
Thank you for the merge. But when I paste the Near Address on the rainbow
bridge assets, it doesn't show the asset image for SFT.

Can you kindly update that metadata for the SFT Asset Icon also?

Many thanks.

**Comment by nvzvhenry** [comment]
Currently, the previous address shows the asset image when the address is pasted on the Rainbow bridge for a new transfer. 
I don't mind if the asset image for that address could be removed, otherwise, kindly help update this new address with the same image so we can publicly push this address out to the community. 

Thank you as I await your swift response.

**Comment by nvzvhenry** [comment]
Hello.

Please can you kindly update the token image for the new address 0aabcc65ef352ad84b1326df188c95b6ab856c1c.factory.bridge.near for the Near platform. 

It's taking longer than expected. 

Thank you

**Comment by nvzvhenry** [comment]
Screenshot 2022-04-19 at 17 05 49

No Image showing.

**Pull request merged**
