### PR TITLE
Add 0xMR token metadata

### PR DESCRIPTION
**Pull request by stupicode**
# Add 0xMR token metadata

ERC-20: https://etherscan.io/address/0x035df12e0f3ac6671126525f1015e47d79dfeddf
NEP-141: https://explorer.mainnet.near.org/accounts/035df12e0f3ac6671126525f1015e47d79dfeddf.factory.bridge.near
Aurora ERC-20 (BlockScout): https://explorer.mainnet.aurora.dev/address/0x7EA2be2df7BA6E54B1A9C70676f668455E329d29
Aurora ERC-20 (Aurorascan): https://aurorascan.dev/address/0x7EA2be2df7BA6E54B1A9C70676f668455E329d29

### CODE REVIEW

**Review by sept-en — CHANGES_REQUESTED** [review]
I see that the token is not bridged through Rainbow Bridge. Moreover, there's still no RB token deployed on Aurora. Could you please clarify that?

**Comment by sept-en** [comment]
@stupicode  I think, in the matter of the current PR, we can merge this PR without `aurora_address` field. And then we can have another PR that contains only an Aurora address, and in tokens list, will have a name with "- Multichain" suffix (similar to Allbridge bridged tokens). Or if you need the token to appear in tokens list, we can do only the part with the suffix in the current PR. WDYT?

**Comment by stupicode** [comment]
near_address added

**Review by stupicode — COMMENTED** [review]
@sept-en near_address added

**Comment by 0xMonero** [comment]
The commit has the svg logo image set to 0 Height 0 Width. Please correct this.

**Pull request closed without merging**
