### PR TITLE
Add NEARIA token metadata

### PR DESCRIPTION
**Pull request by dusan-mrsic**
NEP-141: https://explorer.mainnet.near.org/accounts/near_starter_index_token.near
Aurora ERC-20 (BlockScout): https://explorer.mainnet.aurora.dev/address/0x11fffdcb623b4882daed70eb22c2bf51215178dc
Aurora ERC-20 (Aurorascan): https://aurorascan.dev/address/0x11fffdcb623b4882daed70eb22c2bf51215178dc

### CODE REVIEW

**Comment by dusan-mrsic** [comment]
Hi, I am from https://nearstarter.fi/. Do you have any updates about this pull request?

**Review by sept-en — APPROVED** [review]

**Comment by sept-en** [comment]
@dusan-mrsic sorry, this PR somehow got lost. The metadata on Aurora will be updated during the week.
Also, please note if you need to have the icon available as a part of metadata, your NEP-141 token should have the same icon in its `ft_metadata`. When it's ready, please open a new PR and adjust the `icon` value in the JSON file.

**Comment by mike-tis** [comment]
Hello guys
I see that the NEARIA token is still not available in the bridge. Also both explorers show nothing. Currently we're blocked with the prod release of our service only because of these delays with our tokens. Please help us with it.

**Comment by mike-tis** [comment]
@sept-en please help

**Pull request merged**
