### PR TITLE
[TESTNET] Add rMutantCoin metadata

### PR DESCRIPTION
**Pull request by jirosaito**
# Add rMutantCoin metadata

ERC-20: https://goerli.etherscan.io/address/0x0Eb83Fc829545f941228f6c3A250909CfFB176e0
NEP-141: https://explorer.testnet.near.org/accounts/0eb83fc829545f941228f6c3a250909cffb176e0.factory.goerli.testnet

### CODE REVIEW

**Comment by jirosaito** [comment]
Hi, could someone please help to merge?

**Comment by jirosaito** [comment]
@sept-en could you please help to merge this PR?

**Comment by jirosaito** [comment]
@sept-en could you help with this PR or tag someone who could please? We are blocked to test on Aurora until this PR is merged :(

**Review by sept-en — APPROVED** [review]

**Comment by sept-en** [comment]
Hi @jirosaito! Thanks, merging your PR. The update of the metadata for the Testnet could be delayed, so please contact anton@aurora.dev and he will help you with your efforts and suggest the best way to proceed with testing.

**Pull request merged**
